
package io.dargenn.temp.io.dargenn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://dargenn.io/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://dargenn.io/", className = "io.dargenn.GetHelloWorld")
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://dargenn.io/", className = "io.dargenn.GetHelloWorldResponse")
    @Action(input = "http://dargenn.io/HelloWorld/getHelloWorldRequest", output = "http://dargenn.io/HelloWorld/getHelloWorldResponse")
    public String getHelloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
